project:
  name: test-appsync-automation-project
  regions:
    - ca-central-1
tests:
  appsync-test:
    parameters:
      APIName: "simpleAPI"
      AvailabilityZones: '$[taskcat_genaz_1]'
    template: ./templates/appsync/appsyncApi.template